### ISSUE TITLE
Ram selector

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#107]
Maybe you can add a RAM selector menu, with options for 16kB, 32kB and 64kb (16kB+6x8kB banks)

**Comment by dionoid** [comment]
...actually 64KB = 16KB + 16KB + 4x8KB banks
**_[edit: this was an assumption, based on the current bank-switching code in M2000, which turns out to be wrong]_**

**Comment by yqxq** [comment]
I think it are 6 banks. The expansion board itself has 8x8kB RAM chips. So it has 80kB RAM in total.
Base RAM is 16kB  &H6000-&H9FFF
16kB expansion is &HA000-&HDFFF
the remaining 48kB of a 64kB expansion is &HE000-&HFFFF (8kB) and fits 6 times
You can see it at the product numers
T38=4+16+2+16=38kB total 
T54=4+16+2+16+16=54kB in total
T102=4+16+2+16+16+6*8=102kB in total
