### ISSUE TITLE
Convert CAS to BAS (or how to list the source code of a program)

### ISSUE THREAD

**Issue by rdeveen** [p2000t/M2000#116]
With the LIST command, the source code that is loaded into memory is being dumped to the screen. 
Is there a way to dump the source code from a CAS file to a text file?

**Comment by dionoid** [comment]
Yes, you can use the `LLIST` command to "print" the complete listing, which actually then appends it to the `Printer.out` file located in the M2000 folder within your Documents folder.

**Comment by rdeveen** [comment]
Thanks!

**Comment by yqxq** [comment]
Kan het ook de andere kant op (Plakken als tekstinvoer bijvoorbeeld)
