### ISSUE TITLE
No file written when filename extension is not supplied

### ISSUE THREAD

**Issue by ifilot** [p2000t/M2000#121]
**Behavior**
When you create a screenshot with "Save Screenshot" and only type a bare filename without an extension (e.g. `.png`), no file is written.

**Expected behavior**
If the program cannot write a file because of a missing extension, either an error message should be thrown or the program should append a default extension.

**Comment by dionoid** [comment]
M2000 already should append the default image extension (.png) in case you don't provide an image extension yourself. Could you check if maybe your M2000.cfg file (in the M2000 folder inside the Documents folder) contains some unexpected value for the 'screenshots' setting?

**Comment by ifilot** [comment]
I think I found the culprit, it is a `.` in the pathname. The directory I tried to write to is:
```D:\PROGRAMMING\P2000T\philips-p2000t.nl\docs\source\_static\img\z88dk```

If I choose a directory without a `.` in the path, it works and `.png` is appended.

**Comment by dionoid** [comment]
Thanks for tracking down the source of the bug. Clearly the extension-detection isn't correct here. Luckily the Allegro framework has some util classes for this, which I will use instead of the current extension detection code.

**Comment by dionoid** [comment]
Fixed in main branch (commit efc4989)
