### ISSUE TITLE
Compilation for multiple unix platforms

### ISSUE THREAD

**Issue by zoltanvb** [p2000t/M2000#137]
Hi, I noticed your PR for libretro-super, and decided to add this core also for the unofficial repo of armv7 cores that I maintain.
Can you do a small change in the libretro makefile, so that it is compilable also for "unix-armv7-hf-neon"? This is used by some of the build scripts.

```
-ifeq ($(platform), unix)
+ifneq (,$(findstring unix,$(platform)))

```

**Comment by dionoid** [comment]
Done. Your core collection is [here](https://zoltanvb.github.io/armv7-hf-neon/), right?

**Comment by zoltanvb** [comment]
Thanks a lot! Yes, it is that one.
