### ISSUE TITLE
[libretro CI] build failing for a couple of platforms

### ISSUE THREAD

**Issue by hizzlekizzle** [p2000t/M2000#147]
We have a couple of build failures in the libretro CI pipeline that are preventing it from publishing: https://git.libretro.com/libretro/M2000/-/pipelines/262563 (all pipelines have to finish successfully before it will publish).

Most of them look pretty minor (e.g., looks like Windows build needs -fPIC) and you can probably crib some hints from some other cores' makefiles for more obscure platforms, such as emscripten, if needed. If you can't get a platform to build, though, you can always just disable it in the recipe temporarily to get the rest to publish and then come back and work on the stragglers.

Let me know if you have any questions!

**Comment by warmenhoven** [comment]
For the osx-arm64 build, an intel-based Mac is used to build the cores. The Makefile needs to be altered slightly to be aware of the cross compile. All of the `ARCHFLAGS` stuff can be removed, it was only useful for ppc which is not currently supported. Instead, you need to handle `CROSS_COMPILE` being set and setting the target and isysroot, see https://github.com/libretro/mupen64plus-libretro-nx/blob/3f794eec4dc4af2f22ecce507f2da324381d3d92/Makefile#L411 for an example.

**Comment by dionoid** [comment]
Thanks @hizzlekizzle and @warmenhoven for all the information. I made some changes to the Makefile and now the M2000 builds in the libretro CI pipeline are all green!
