### ISSUE TITLE
Should we remove the code for joystick support?

### ISSUE THREAD

**Issue by dionoid** [p2000t/M2000#19]
Joystick isn't supported in the Allegro version, and for the Linux version it's disabled by default.
I don't think anyone uses this and it isn't tested.
Also, why support a joystick on a system that only had a keyboard?

Needs discussion before we decide to remove the joystick code.

**Comment by ifilot** [comment]
My proposal would be to have the functionality behind a compilation guard (e.g. `-DJOYSTICK`), clearly documenting this as an experimental feature with poor support over the platforms.

Allegro has [joystick support](https://www.allegro.cc/manual/5/joystick.html) so this functionality could potentially be added, though I (also) have the impression this functionality is not really used. From the discussions on Retroforum, it seems that only a marginal number of users had a joystick on their P2000T, requiring some custom SLOT2 hardware.

**Comment by dionoid** [comment]
> From the discussions on Retroforum, it seems that only a marginal number of users had a joystick on their P2000T, requiring some custom SLOT2 hardware.

Yes, I also learned from the discussion on Retroforum that indeed there was a way of playing joysticks on the original P2000T by using a special cartridge. So I agree this feature should stay in then. Adding joystick support using the Allegro libs seems like something that is not that complicated.

**Comment by dionoid** [comment]
Closing this issue
