### ISSUE TITLE
Current build procedure is doing 'zipception'

### ISSUE THREAD

**Issue by ifilot** [p2000t/M2000#20]
A zip within a zip is produced in the current build procedure. Do not offer the .zip file as the build artifact but the separate files.

**Comment by ifilot** [comment]
Feel free to assign this issue to me. :-)

**Comment by dionoid** [comment]
Looks like the issue is still there after the fix was merged?

**Comment by ifilot** [comment]
I do not see the issue. For example: your last pull request resulted in Github Actions being triggered. A **single** m2000win.zip file was produced that contains all the files to launch the emulator under Windows. Also see the screenshot below:

![Screenshot 2023-10-20 073130](https://github.com/p2000t/M2000/assets/1659768/20b9a88c-5139-496b-a55d-a4341ea68851)

If you still see a 'zip in zip' somewhere, please let me know where you observed this so that I can retrace what went wrong.

**Comment by dionoid** [comment]
It's not a 'zip in a zip' anymore, but the filename is `m2000win.zip.zip`:
![image](https://github.com/p2000t/M2000/assets/3540187/675e54cc-5b6e-4e78-9aeb-2aa505573717)

I suppose in your Windows file explorer, you have the viewing of "File name extensions" unchecked (which is the default).

**Comment by ifilot** [comment]
OK, that was rather silly on my side. :sweat_smile: I forgot that Github Actions appends `.zip` to the artifact name. I have fixed this in #23 .

**Comment by ifilot** [comment]
And with that last item, I think we can safely say this issue is resolved. :smile:
