### ISSUE TITLE
Establishing community policy and adjusting source file headers

### ISSUE THREAD

**Issue by ifilot** [p2000t/M2000#46]
I believe it clearly stands that this repository contains a serious advancement of the venerable M2000 emulator, supporting modern operating systems and being actively maintained. It would serve the larger community to point this out. I kindly suggest (and open for debate!) to make the following changes:

- [ ] Adjust the headers in the source files to indicate that they belong to this repository and who the current maintainers / developers are.
- [ ] Adjust the source files mentioning the current license (I assume lGPL-v3 is the best).
- [ ] Add a LICENSE.md file to the repository.
- [ ] Contact the original developer and seek active approval for adjusting the license details, ensuring their right for proper attribution is actively being maintained.
- [ ] Add a `community.md` file explaining how end-users can produce issues and how developers can offer pull requests.

I am happy to take any of these tasks upon me.

**Comment by ifilot** [comment]
I can take tasks 1,2,3 and 5 upon me without any problem (please feel free to assign this issue to me). I am also happy to take task 4 upon me, though I think it would be best if @dionoid as the repository maintainer would do this. Just let me know your thoughts on this.

**Comment by dionoid** [comment]
I've reached out to Marcel; I'll let you know as soon as I get a response from him. Let's work on the other tasks as we get a response.

**Comment by dionoid** [comment]
> I've reached out to Marcel; I'll let you know as soon as I get a response from him. Let's work on the other tasks as we get a response.

I was unable to reach Marcel. I've tried LinkedIn, Facebook messenger and the info address of his own domain, but got no response.

**Comment by ifilot** [comment]
Sure, I will give it a go. If we get absolutely no response, we can consider the code as abandonware aiming to stick to the author's original intentions as close as possible (which we are already doing).
