### ISSUE TITLE
Symbolic keyboard mapping

### ISSUE THREAD

**Issue by dionoid** [p2000t/M2000#5]
The current M2000 keyboard mapping is "positional", i.e., based on the position of the keys on an original P2000 keyboard. E.g. the "&" character is mapped to Shift-6 instead of Shift-7, which is what modern PC/laptop keyboards use. 
This mapping can be frustrating, as a lot of P2000 keys are mapped to a different position, when compared to modern keyboards.
We need an optional symbolic keyboard mapping, so what you type on your keyboard is what you'll see on the screen (mostly).

![image](https://github.com/p2000t/M2000/assets/3540187/f2caf95c-34b0-42b1-847f-fac8e2c25b74)

**Comment by yqxq** [comment]
My suggestion is to follow the real keyboard layout, and add this:
[ as ←
] as →
~ as ÷
| as ‖
\ as █
{ as ¼
} as ¾
` as ½
^ as ↑
_ as – (long dash ascii 96)
And with alt/altg or FN for laptops, including alt-shift support for cassette keys (the numpad is printed on my DELL laptop in a similar manner in blue to be combined with the FN key)
789 as numpad 789 (with shift wipe disk, ø en M)
uio as 456 (with shift INL - OPN)
jkl as 123 (with shift zoek, serial, start)
m,. as 0, 00, . (and with shift def-prnt-stop)
del as clr-screen (÷ and * have a location already)

**Comment by dionoid** [comment]
> My suggestion is to follow the real keyboard layout, and add this: [ as ← ] as → ~ as ÷ | as ‖ \ as █ { as ¼ } as ¾ ` as ½ ^ as ↑ _ as – (long dash ascii 96) And with alt/altg or FN for laptops, including alt-shift support for cassette keys (the numpad is printed on my DELL laptop in a similar manner in blue to be combined with the FN key) 789 as numpad 789 (with shift wipe disk, ø en M) uio as 456 (with shift INL - OPN) jkl as 123 (with shift zoek, serial, start) m,. as 0, 00, . (and with shift def-prnt-stop) del as clr-screen (÷ and * have a location already)

Hi @yqxq , some of your suggested characters aren't available on the P2000 keyboard, like ÷, ‖ and ½. The others are great suggestions and will be implemented.
Note that the keyboard emulation in M2000 is very low-level and done by emulating the keyboard matrix. The P2000 rom (monitor) is taking care of reading the resulting keycodes and putting them into the keyboard input buffer, just as in an actual P2000.

As for numeric pad emulation: for those who have a keyboard with numeric pad (or in your case, can simulate a num pad by using FN key + 789/UIO/JKL/M,.) these will still be supported like in the current version. But for those without a num pad (or FN key mappings to simulate that), I don't think we should have complex mappings like pressing Alt-Shift-J to run a ZOEK command; the point of this enhancement is to keep it simple and match the symbols on the PC's keyboard :)
What if I add these additional function-key mappings:

```
- F1         = ZOEK key   (show cassette index)
- F2         = START key (start loaded program)
- Shift + F2 = STOP key    (pause/halt program)
```
