### ISSUE TITLE
Active cassette title in window bar

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#50]
Please list the active tape and location in the window header bar.
Also if you do a reset, without a tape, you get a "geen cassette" error. This does not happen on first boot, or on a real machine.

**Comment by dionoid** [comment]
> Please list the active tape and location in the window header bar.

Good suggestion

> Also if you do a reset, without a tape, you get a "geen cassette" error. This does not happen on first boot, or on a real machine.

Reset emulates pressing the "R" button next to the MCR, so this is not a full reboot.

**Comment by yqxq** [comment]
Pressing the R button does not give a "No cassette warning" either.

**Comment by dionoid** [comment]
> Pressing the R button does not give a "No cassette warning" either.

Yes, you are right. Need to fix that.
