### ISSUE TITLE
120% Speed request

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#53]
Since the machine runs at 50fps, and most computers run at 60fps, it would be nice to have stutter free 120% speed.

**Comment by dionoid** [comment]
Actually, we need an option to choose the FPS (50, 60), so the relation to the monitor's refresh rate is more clear

**Comment by dionoid** [comment]
![image](https://github.com/p2000t/M2000/assets/3540187/5476c658-c876-446c-817e-583496a984e1)
