### ISSUE TITLE
Editable preference file

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#54]
Maybe you can work with a readable preference file containing things like:

- window size/position
- key mapping
- language
- scanlines setting
- default folder for loading tapes
- default folder for ROMS
- default folder for screenshots
- name prefix for screenshots
- ram amount
- black/white/green/amber display
- RGB values for colour 0-7 so one can make it monochrome or b&w.

**Comment by dionoid** [comment]
M2000 currently supports a M2000.cfg file in the same directory as the executable, which you can use to set default options.

![image](https://github.com/p2000t/M2000/assets/3540187/8fa33d56-42b8-4026-9180-c841ca07a9e9)
