### ISSUE TITLE
Produce compilation for Ubuntu in Gitlab Actions

### ISSUE THREAD

**Issue by dionoid** [p2000t/M2000#57]
Todo: figure out how to get static Allegro libs and how to package them with the M2000 binary

**Comment by ifilot** [comment]
I have a suggestion
Allegro 5 is natively supported on Ubuntu and the recommended implementation is then to use dynamic linking. We could take one of the LTS versions of Ubuntu and create a .deb package around M2000. The user can then simply download the .deb package and install it with `dpkg -i m2000.deb` or so. A more ambitious plan, but also most professional, would be to publish M2000 via a [Personal Package Archive](https://help.launchpad.net/Packaging/PPA) (PPA).

Anyway, for a simple Ubuntu compilation Github Actions with the intention to verify that the compilation works under Ubuntu, you can assign this issue to me. Unless you want to adopt this issue yourself for the learning experience of course. 😉

**Comment by dionoid** [comment]
Great suggestion. Indeed I see there is a "liballegro5.2" debian package, which has the most recent version of Allegro 5 libs. On the build machine you'll need the liballegro5-dev package then. Assigning to you :)
