### ISSUE TITLE
Add Open and CLOAD

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#64]
Now you can either Open a .cas or open, cload and run a cas.
My most used action is open+cload.
Not sure if it can be implemented, but maybe the program can check if a tape contains more than one program, and give a open+index (shift-1) combination in that case.

**Comment by dionoid** [comment]
The "Open, load and run" feature is actually just loading the tape and then doing a Reset (black button next to the MDCR), so it's not entering BASIC commands.
The F1 key is currently mapped to Shift-Numeric1, so showing the index is just a one-button click.

I'm not sure if we want the emulator to start typing in commands, but it could indeed save BASIC users some time.
