### ISSUE TITLE
Allow drag & drop of .cas or .bin files onto M2000 executable

### ISSUE THREAD

**Issue by dionoid** [p2000t/M2000#7]
I'd like to drag a game's .cas file and then drop it onto m2000win.exe to directly start the M2000 emulator with the game booted. Should work for Linux also.
"Drag, drop and play"

**Comment by ifilot** [comment]
For this functionality, you ideally want to have a drop event like [the GLFW library is offering](https://www.glfw.org/docs/3.3/group__input.html#gab773f0ee0a07cff77a210cea40bc1f6b). Unfortunately, Allegro does not (yet) support such a functionality. There was an [attempt in 2014](https://www.allegro.cc/forums/thread/614921), but it did not came to fruition.

I reckon a workaround has to be found for this. A few suggestions that come to mind (all open for discussion of course):
* Write a wrapper GUI that allows drag and drop (this GUI could also potentially interface with a repository of P2000T programs)
* Use the [native dialogs functionality](https://liballeg.org/a5docs/trunk/native_dialog.html) of Allegro, noting that this is not supported on DOS.
* Exchange Allegro for a more feature-rich environment like [GLFW](https://www.glfw.org/) or [Qt](https://www.qt.io/). This *might* not even be as such work as it seems. I have the impression that the connection to Allegro was well-developed and only requires a few connections.

**Comment by dionoid** [comment]
I think with the new menu feature in M2000 0.7, it's already a lot easier for users to load a .cas/.bin file.

**Comment by dionoid** [comment]
Until Allegro comes with a drag&drop update, we're going to close this issue.
