### ISSUE TITLE
Mac version keyboard bug

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#78]
<img width="784" alt="Schermafbeelding 2023-11-13 om 07 00 48" src="https://github.com/p2000t/M2000/assets/145245534/5df804f9-2cbf-49bd-b21a-dbc71206ff6f">
The Mac version has keyboard issues. Sometimes one keypress is read as many. I typed CLOAD and the o got stuck, even through a reset-cycle as you see on the picture.
Also if you reset-load-run say Fraxxon, it goes straight to the screen with centipuul, centrifuul etc., as if a ghost key was pressed at the title screen.

**Comment by dionoid** [comment]
I noticed this problem on my MacBook only when holding the Cmd key while pressing another key. I think this is a bug in the keyboard handler of the macOS allegro libs. Pressing the "stuck" key again will fix it, but is a poor workaround.
Can you reproduce this issue also *without* pressing the Cmd key?

**Comment by yqxq** [comment]
I did not use the CMD key at all as there was no reason to use it.

**Comment by dionoid** [comment]
Seems to be related to this allegro issue: https://github.com/liballeg/allegro5/issues/728
