### ISSUE TITLE
4 op een Rij render issues

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#9]
The 4 op een rij game does not render correctly. All discs are shown as text. Manually rendering the video memory dump is correct.
![rendering from memory dump](https://github.com/p2000t/M2000/assets/145245534/d2941ba0-a2a6-4f43-b249-8e2819f82857)

**Comment by yqxq** [comment]
Seems to be caused my rendering of conceiled character dec 24 or hex 18

**Comment by dionoid** [comment]
Good find! Did you check on a real P2000T if the problem is there with the same .cas file?

**Comment by dionoid** [comment]
I found some helpful documentation of the Teletext specification here: https://www.bighole.nl//pub/mirror/homepage.ntlworld.com/kryten_droid/teletext/spec/teletext_spec_1974.htm

Using this specification, I could track down a bug in the M2000 Teletext character handling.

![image](https://github.com/p2000t/M2000/assets/3540187/31308506-d5ad-409e-ab2a-22e014225f9a)

**Comment by dionoid** [comment]
Fixed!

Old screen:

![image](https://github.com/p2000t/M2000/assets/3540187/8ecbece0-48ab-4877-ac8e-19572a173bba)

New screen:

![image](https://github.com/p2000t/M2000/assets/3540187/df735065-d5fc-491f-b195-2dcea8b8cc61)
